package com.erpnext.framework.web.message;

import org.springframework.http.HttpStatus;

public class ErrorInfo {
	
	/**
    * A short, human-readable summary of the problem type. It SHOULD NOT
    * change from occurrence to occurrence of the problem, except for purposes
    * of localization.
    */
	private String error;
	
	/**
     * The HTTP status code generated by the origin server for this occurrence
     * of the problem.
     */
    private Integer status;

    /**
     * An human readable explanation specific to this occurrence of the
     * problem.
     */
    private String detail;
    
    public ErrorInfo(){}
    
    public ErrorInfo(ErrorInfo orig) {
        this.error = orig.getError();
        this.status = orig.getStatus();
        this.detail = orig.getDetail();
    }

	public String getError() {
		return error;
	}

	public void setError(String error) {
		this.error = error;
	}

	public Integer getStatus() {
		return status;
	}

	public void setStatus(Integer status) {
		this.status = status;
	}
	
	public void setStatus(HttpStatus status) {
        this.status = status.value();
    }

	public String getDetail() {
		return detail;
	}

	public void setDetail(String detail) {
		this.detail = detail;
	}
    
    

}
